[pytest]
log_cli = 1
log_format = %(asctime)s %(levelname)s %(message)s
log_date_format = %Y-%m-%d %H:%M:%S
log_cli_level = INFO
log_cli_format = %(asctime)s %(levelname)s %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S
markers =
    smoke: быстрые тесты
    regression: регрессионные тесты
    slow: медленные тесты
    api: API-тесты
    ui: IU-тесты
    db: DB-тесты
    auth_smoke: быстрые smoke‑тесты для аутентификации
    movies_smoke: быстрые smoke‑тесты для Movies API
    user_smoke: быстрые smoke‑тесты для User API
    mock_smoke: smoke‑тесты для mock/fake сценариев
    transactions_smoke: smoke‑тесты для транзакций/DB сценариев
    flaky: нестабильные/флейковые тесты (пересмотреть или пометить на перезапуск)